version: "3.8"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_UPSTREAM: http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:3306
    image: springboot/medmanagementapp_docker:V0.0.3
